### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by tass-ewoudvc** [m-labs/asyncserial#3]
Hi,
Would there by any way for you to implement timeouts on this library.
The interface seems to hint at you wanting that feature as well, but currently it's hardcoded to raise an exception.

Or any advice on how to implement in your library ourselves

Thanks

**Comment by sbourdeauducq** [comment]
Can't you use ``asyncio.wait_for``?

**Comment by tass-ewoudvc** [comment]
Sorry for the late reply, thought I was going to get notified of a reply by GitHub

We did use `wait_for` in the end;  
Wrote a minimal wrapper class to do the `wait_for`, and that forwards all other calls automatically to your port. (code that uses it is asyncio agnostic)

Should you be interested in the wrapper, let me know, I'll try my first PR then.

**Comment by sbourdeauducq** [comment]
> We did use wait_for in the end;

OK.

> Wrote a minimal wrapper class to do the wait_for, and that forwards all other calls automatically to your port. (code that uses it is asyncio agnostic)

What does that mean exactly?
