### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by Justin318** [m-labs/asyncserial#4]
Install using 

`conda install asyncserial `

successful but import using
import asyncserial return the errror message

`ImportError: No module named 'asyncserial'`

System: 64-bit windows system with anaconda python 3.5

**Comment by sbourdeauducq** [comment]
Did you update conda?

**Comment by Justin318** [comment]
i was trying to install it in a newly created environment using

`conda install --name bunny python=3.5 anaconda
`

**Comment by sbourdeauducq** [comment]
Do ``conda update conda`` before that.

**Comment by Justin318** [comment]
Anaconda raise the error:
Error: Package 'conda' is not installed in --- env
